# Generated by Django 5.2.10 on 2026-03-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_institution_saas_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='institution_type',
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('COACHING', 'Coaching')], default='SCHOOL', max_length=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
