# Generated by Django 5.2.10 on 2026-03-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_rename_amount_feestructure_total_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
