"""
Django settings for ems project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse
import os
import importlib
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Helpers for environment-based configuration
def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    return [item.strip() for item in value.split(',') if item.strip()]


def database_from_url(db_url):
    parsed = urlparse(db_url)
    engine_map = {
        'postgres': 'django.db.backends.postgresql',
        'postgresql': 'django.db.backends.postgresql',
        'mysql': 'django.db.backends.mysql',
        'sqlite': 'django.db.backends.sqlite3',
    }
    engine = engine_map.get(parsed.scheme)
    if not engine:
        return None

    if engine == 'django.db.backends.sqlite3':
        db_path = parsed.path.lstrip('/') or str(BASE_DIR / 'db.sqlite3')
        return {'ENGINE': engine, 'NAME': db_path}

    return {
        'ENGINE': engine,
        'NAME': parsed.path.lstrip('/'),
        'USER': parsed.username or '',
        'PASSWORD': parsed.password or '',
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
    }


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-secret-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

# Optional: enable a temporary test mode for debugging CSRF issues.
# Set the environment variable `CSRF_TEST_MODE=1` to force DEBUG=True
# without changing production config permanently.
if os.getenv('CSRF_TEST_MODE') == '1':
    DEBUG = True

default_allowed_hosts = [
    '127.0.0.1',
    'localhost',
    'aaditech2.pythonanywhere.com',
]
if DEBUG:
    default_allowed_hosts.extend([
        '10.162.61.218',
        '.trycloudflare.com',
    ])

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', default_allowed_hosts)

default_csrf_trusted = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://aaditech2.pythonanywhere.com',
]
if DEBUG:
    default_csrf_trusted.extend([
        'http://10.162.61.218:8000',
        'http://*.trycloudflare.com',
        'https://*.trycloudflare.com',
    ])

if DEBUG:
    csrf_default = default_csrf_trusted
else:
    csrf_default = [
        f'https://{host}'
        for host in ALLOWED_HOSTS
        if host and not host.startswith('.')
    ]

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS', csrf_default)

# Ensure the PythonAnywhere origin is present in trusted origins (idempotent)
if 'https://aaditech2.pythonanywhere.com' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append('https://aaditech2.pythonanywhere.com')
# Also ensure the main deployment host is present in ALLOWED_HOSTS
if 'aaditech2.pythonanywhere.com' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('aaditech2.pythonanywhere.com')

# Configure a CSRF failure view and logging to help debugging CSRF 403s.
CSRF_FAILURE_VIEW = 'ems.views.csrf_failure'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.security.csrf': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'ERROR',
            'propagate': True,
        },
    },
}

# Rate limiting (per IP, per path)
RATE_LIMIT_WINDOW = 60
RATE_LIMIT_REQUESTS = 120

# Security hardening (production-safe defaults)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Session configuration defaults (can be overridden via environment variables)
SESSION_ENGINE = os.getenv('SESSION_ENGINE', 'django.contrib.sessions.backends.db')
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', '1209600'))  # default 2 weeks
SESSION_SAVE_EVERY_REQUEST = env_bool('SESSION_SAVE_EVERY_REQUEST', True)

# Ensure the primary PythonAnywhere host is trusted for CSRF (idempotent)
if 'https://aaditech2.pythonanywhere.com' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append('https://aaditech2.pythonanywhere.com')

if not DEBUG:
    if SECRET_KEY == 'dev-secret-key-change-me':
        raise RuntimeError('Set DJANGO_SECRET_KEY in production.')
    if not os.getenv('DJANGO_ALLOWED_HOSTS'):
        raise RuntimeError('Set DJANGO_ALLOWED_HOSTS in production.')
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'accounts',
    'communications',
    'core',
    'dashboard',
    'materials',
    'billing',
    'ai_services',
    'analytics',
    'institutions',
    'classes',
    'attendance',
    'exams',
    'fees',
    'notices',
    'notifications',
    'students',
    'teachers',
    'documents',
    'reports',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTH_USER_MODEL = 'accounts.User'



# Insert WhiteNoise middleware only if the package is available to avoid
# crashing the WSGI app when the dependency isn't installed.
_MIDDLEWARE_BASE = [
    'django.middleware.security.SecurityMiddleware',
    'ems.middleware.RateLimitMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dashboard.middleware.ActivityLogMiddleware',
]

# Safe attempt to enable whitenoise if it's installed
try:
    importlib.import_module('whitenoise')
    MIDDLEWARE = _MIDDLEWARE_BASE[:]
    # place WhiteNoise right after SecurityMiddleware
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
except Exception:
    logging.getLogger(__name__).warning('whitenoise not installed; skipping WhiteNoiseMiddleware')
    MIDDLEWARE = _MIDDLEWARE_BASE

ROOT_URLCONF = 'ems.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates',
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.template.context_processors.csrf',
            'ems.context_processors.static_version',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
        },
    },
]

WSGI_APPLICATION = 'ems.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


database_url = os.getenv('DATABASE_URL')
database_from_env = database_from_url(database_url) if database_url else None

if database_from_env:
    DATABASES = {'default': database_from_env}
elif os.getenv('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
            'NAME': os.getenv('DB_NAME', ''),
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', ''),
            'PORT': os.getenv('DB_PORT', ''),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('hi', 'Hindi'),
]

USE_I18N = True
USE_L10N = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
TIME_ZONE = 'UTC'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    path for path in (BASE_DIR / 'static', BASE_DIR / 'templates' / 'static') if path.exists()
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Prefer WhiteNoise storage if available; fall back to default storage otherwise.
try:
    importlib.import_module('whitenoise')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
except Exception:
    logging.getLogger(__name__).warning('whitenoise not installed; using default staticfiles storage')
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# AI / external service settings
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4.1-mini')
OPENAI_API_BASE = os.getenv('OPENAI_API_BASE', 'https://api.openai.com/v1')

# Static cache busting
STATIC_VERSION = os.getenv('STATIC_VERSION', '20260311-4')
