# Generated by Django 5.2.10 on 2026-03-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_end_date_exam_date_remove_exam_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
