# Generated by Django 5.2.10 on 2026-03-19 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_teacher_name_if_exists(apps, schema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    table_name = Teacher._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        ]
    if 'name' in columns:
        schema_editor.remove_field(Teacher, Teacher._meta.get_field('name'))


def _add_field_if_missing(schema_editor, model, field):
    table_name = model._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        ]
    if field.column not in columns:
        schema_editor.add_field(model, field)


def add_institution_if_missing(apps, schema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    Institution = apps.get_model('core', 'Institution')
    field = models.ForeignKey(
        Institution,
        on_delete=django.db.models.deletion.CASCADE,
        related_name='teachers',
        null=True,
        blank=True,
    )
    field.set_attributes_from_name('institution')
    field.model = Teacher
    _add_field_if_missing(schema_editor, Teacher, field)


def add_qualification_if_missing(apps, schema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    field = models.CharField(max_length=100, blank=True, default='')
    field.set_attributes_from_name('qualification')
    field.model = Teacher
    _add_field_if_missing(schema_editor, Teacher, field)


def add_user_if_missing(apps, schema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    User = apps.get_model('accounts', 'User')
    field = models.OneToOneField(
        User,
        on_delete=django.db.models.deletion.CASCADE,
        related_name='teacher_profile',
        null=True,
        blank=True,
    )
    field.set_attributes_from_name('user')
    field.model = Teacher
    _add_field_if_missing(schema_editor, Teacher, field)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsletter_subscription'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_teacher_name_if_exists,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='teacher',
                    name='name',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_institution_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='teacher',
                    name='institution',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.institution'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_qualification_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='teacher',
                    name='qualification',
                    field=models.CharField(blank=True, default='', max_length=100),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_user_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='teacher',
                    name='user',
                    field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
