# Generated by Django 5.2.10 on 2026-01-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('coaching', 'Coaching')], max_length=20)),
                ('address', models.TextField()),
                ('session_start', models.DateField()),
                ('session_end', models.DateField()),
            ],
        ),
    ]
